weights: C:\Users\ADMIN\Desktop\Project\yolov5\runs\train\Model10\weights\last.pt
cfg: C:\Users\ADMIN\Desktop\Project\yolov5\models\yolov5s.yaml
data: C:\Users\ADMIN\Desktop\Project\yolov5\data\data.yaml
hyp: data\hyps\hyp.scratch-low.yaml
epochs: 5
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: Model
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\Model11
